//FIXME: this should either come from SnowflakeDB or contain all the country codes
const COUNTRY_CODES = {
  AFG: 'Afghanistan',
  ARM: 'Armenia',
  BGD: 'Bangladesh',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  BDI: 'Burundi',
  KHM: 'Cambodia',
  CAF: 'Central African Republic',
  TCD: 'Chad',
  CHN: 'China',
  COL: 'Colombia',
  COD: 'Democratic Republic of the Congo',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  SLV: 'El Salvador',
  ETH: 'Ethiopia',
  GEO: 'Georgia',
  GHA: 'Ghana',
  GTM: 'Guatemala',
  HTI: 'Haiti',
  HND: 'Honduras',
  IND: 'India',
  IDN: 'Indonesia',
  IRQ: 'Iraq',
  // TBD: ' TBD - Jerusalem - West Bank - Gaza',
  KEN: 'Kenya',
  LAO: 'Laos',
  LBN: 'Lebanon',
  MWI: 'Malawi',
  MLI: 'Mali',
  MRT: 'Mauritania',
  MEX: 'Mexico',
  MNG: 'Mongolia',
  MOZ: 'Mozambique',
  NPL: 'Nepal',
  NIC: 'Nicaragua',
  NER: 'Niger',
  PER: 'Peru',
  PHL: 'Philippines',
  RWA: 'Rwanda',
  SEN: 'Senegal',
  SLE: 'Sierra Leone',
  SOM: 'Somalia',
  // SSD: '[x] South Sudan', - missing geojson file for region
  LKA: 'Sri Lanka',
  SDN: 'Sudan',
  SSD: 'South Sudan',
  SYR: 'Syria Response (Turkey, Jordan, Syria)',
  TZA: 'Tanzania',
  UGA: 'Uganda',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
  AGO: 'Angola',
  MMR: 'Myanmar',
  UKR: 'Ukraine Response (Ukraine, Romania, Moldova)'
}

const COUNTRY_NAMES = Object.fromEntries(
  Object.entries(COUNTRY_CODES).map(([key, value]) => [value, key])
)
export { COUNTRY_CODES, COUNTRY_NAMES }
