const COUNTRY_CODES = {
    AFG: 'Afghanistan',
    ARM: 'Armenia',
    BGD: 'Bangladesh',
    BOL: 'Bolivia',
    BRA: 'Brazil',
    BDI: 'Burundi',
    KHM: 'Cambodia',
    CAF: 'Central African Republic',
    TCD: 'Chad',
    CHN: 'China',
    COL: 'Colombia',
    COD: 'Democratic Republic of the Congo',
    DOM: 'Dominican Republic',
    ECU: 'Ecuador',
    SLV: 'El Salvador',
    ETH: 'Ethiopia',
    GEO: 'Georgia',
    GHA: 'Ghana',
    GTM: 'Guatemala',
    HTI: 'Haiti',
    HND: 'Honduras',
    IND: 'India',
    IDN: 'Indonesia',
    IRQ: 'Iraq',
    TBD: ' TBD - Jerusalem - West Bank - Gaza',
    KEN: 'Kenya',
    LAO: 'Laos',
    LBN: 'Lebanon',
    MWI: 'Malawi',
    MLI: 'Mali',
    MRT: 'Mauritania',
    MEX: 'Mexico',
    MNG: 'Mongolia',
    MMR: 'Mozambique',
    NPL: 'Nepal',
    NIC: 'Nicaragua',
    NER: 'Niger',
    PER: 'Peru',
    PHL: 'Philippines',
    RWA: 'Rwanda',
    SEN: 'Senegal',
    SLE: 'Sierra Leone',
    SOM: 'Somalia',
    SSD: 'South Sudan',
    LKA: 'Sri Lanka',
    SDN: 'Sudan',
    SYR: 'Syria Response (Turkey, Jordan, Syria)',
    TZA: 'Tanzania',
    UGA: 'Uganda',
    ZMB: 'Zambia',
    ZWE: 'Zimbabwe',
    AGO: 'Angola',
    MMR: 'Myanmar',
    UKR: 'Ukraine Response (Ukraine, Romania, Moldova)'
  }

  export { COUNTRY_CODES }